# Generated by Django 5.0.14 on 2025-10-10 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='tipo',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('tecnico', 'Técnico'), ('ia', 'IA')], default='usuario', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
