# Generated by Django 5.1.7 on 2025-05-23 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Grado')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Responsable')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
            },
        ),
        migrations.CreateModel(
            name='AtencionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=100, verbose_name='Nombre del Estudiante')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('tratamiento', models.TextField(verbose_name='Tratamiento')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfermeria.grado', verbose_name='Grado')),
                ('atendido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfermeria.medico', verbose_name='Atendido por')),
            ],
            options={
                'verbose_name': 'Atención Médica',
                'verbose_name_plural': 'Atenciones Médicas',
            },
        ),
        migrations.CreateModel(
            name='InventarioMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Medicamento')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('cantidad_existente', models.PositiveIntegerField(verbose_name='Cantidad Existente')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfermeria.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='UsoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.PositiveIntegerField(verbose_name='Cantidad Usada')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('fecha_uso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Uso')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='enfermeria.inventariomedicamento')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfermeria.responsable', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Uso de Medicamento',
                'verbose_name_plural': 'Usos de Medicamentos',
            },
        ),
    ]
