# Generated by Django 5.1.7 on 2025-06-05 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Presentación')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
            },
        ),
        migrations.AlterModelOptions(
            name='grado',
            options={'verbose_name': 'Grado', 'verbose_name_plural': 'Grados'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AddField(
            model_name='inventariomedicamento',
            name='presentacion',
            field=models.ForeignKey(blank=True, help_text='Selecciona blíster, ml, crema, roll-on, etc.', null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermeria.presentacion', verbose_name='Presentación'),
        ),
    ]
