# Generated by Django 5.1.7 on 2025-04-23 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo de Falla')),
            ],
            options={
                'verbose_name': 'Tipo de Falla',
                'verbose_name_plural': 'Tipos de Falla',
                'db_table': 'tipo_falla',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=50, verbose_name='ID del Equipo')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serie', models.CharField(max_length=100, verbose_name='Serie')),
                ('teacher_name', models.CharField(max_length=100, verbose_name='Nombre del Maestro')),
                ('grade', models.CharField(max_length=100, verbose_name='Grado')),
                ('solucion', models.TextField(blank=True, null=True, verbose_name='Solución Aplicada')),
                ('date', models.DateField(verbose_name='Fecha del Mantenimiento')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado')], max_length=50, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('tipo_falla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.tipofalla', verbose_name='Tipo de Falla')),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'verbose_name_plural': 'Registros de Mantenimiento',
                'db_table': 'maintenance_record',
            },
        ),
    ]
