# Generated by Django 5.0.14 on 2025-06-06 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblPrsDtosGen',
            fields=[
                ('PersonaID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Nombre1', models.CharField(blank=True, max_length=100, null=True)),
                ('Nombre2', models.CharField(blank=True, max_length=100, null=True)),
                ('Apellido1', models.CharField(blank=True, max_length=100, null=True)),
                ('Apellido2', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=254, null=True)),
                ('Email2', models.CharField(blank=True, max_length=254, null=True)),
                ('Email3', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'dbo.tblPrsDtosGen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Grado')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Profesional')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Presentación')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Responsable')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
            },
        ),
        migrations.CreateModel(
            name='AtencionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=100, verbose_name='Nombre del Estudiante')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('tratamiento', models.TextField(verbose_name='Tratamiento')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfermeria2.grado', verbose_name='Grado')),
                ('atendido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfermeria2.medico', verbose_name='Atendido por')),
            ],
            options={
                'verbose_name': 'Atención Médica',
                'verbose_name_plural': 'Atenciones Médicas',
            },
        ),
        migrations.CreateModel(
            name='InventarioMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Medicamento')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('cantidad_existente', models.PositiveIntegerField(verbose_name='Cantidad Existente')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('presentacion', models.ForeignKey(blank=True, help_text='Selecciona blíster, ml, crema, roll-on, etc.', null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermeria2.presentacion', verbose_name='Presentación')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfermeria2.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='UsoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.PositiveIntegerField(verbose_name='Cantidad Usada')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('fecha_uso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Uso')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='enfermeria2.inventariomedicamento')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfermeria2.responsable', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Uso de Medicamento',
                'verbose_name_plural': 'Usos de Medicamentos',
            },
        ),
    ]
