# Generated by Django 5.0.14 on 2025-09-02 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncisoConductual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('leve', 'Leve'), ('grave', 'Grave'), ('muy_grave', 'Muy Grave')], max_length=10, verbose_name='Tipo de Inciso')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del inciso')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Inciso Conductual',
                'verbose_name_plural': 'Incisos Conductuales',
                'ordering': ['tipo', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id', models.CharField(max_length=50, verbose_name='ID Alumno')),
                ('alumno_nombre', models.CharField(max_length=120, verbose_name='Nombre del Alumno')),
                ('grado', models.CharField(max_length=50, verbose_name='Grado')),
                ('semana_inicio', models.DateField(verbose_name='Semana inicio')),
                ('semana_fin', models.DateField(verbose_name='Semana fin')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('materias_json', models.JSONField(blank=True, null=True, verbose_name='Detalle materias')),
                ('comentario_general', models.TextField(blank=True, null=True, verbose_name='Comentario General')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reporta')),
            ],
            options={
                'verbose_name': 'Progress Report',
                'verbose_name_plural': 'Progress Reports',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReporteConductual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('bilingue', 'Bilingüe'), ('colegio', 'Colegio/CFP')], default='bilingue', max_length=10, verbose_name='Área')),
                ('alumno_id', models.CharField(max_length=50, verbose_name='ID Alumno')),
                ('alumno_nombre', models.CharField(max_length=120, verbose_name='Nombre del Alumno')),
                ('grado', models.CharField(max_length=50, verbose_name='Grado')),
                ('materia', models.CharField(max_length=100, verbose_name='Materia')),
                ('docente', models.CharField(max_length=100, verbose_name='Docente')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('leve', models.BooleanField(default=False, verbose_name='Leve')),
                ('grave', models.BooleanField(default=False, verbose_name='Grave')),
                ('muy_grave', models.BooleanField(default=False, verbose_name='Muy grave')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario adicional')),
                ('inciso_grave', models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo': 'grave'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductuales_grave', to='conducta.incisoconductual', verbose_name='Inciso Grave')),
                ('inciso_leve', models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo': 'leve'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductuales_leve', to='conducta.incisoconductual', verbose_name='Inciso Leve')),
                ('inciso_muy_grave', models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo': 'muy_grave'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductuales_muy_grave', to='conducta.incisoconductual', verbose_name='Inciso Muy Grave')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reporta')),
            ],
            options={
                'verbose_name': 'Reporte Conductual',
                'verbose_name_plural': 'Reportes Conductuales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReporteInformativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('bilingue', 'Bilingüe'), ('colegio', 'Colegio/CFP')], default='bilingue', max_length=10, verbose_name='Área')),
                ('alumno_id', models.CharField(max_length=50, verbose_name='ID Alumno')),
                ('alumno_nombre', models.CharField(max_length=120, verbose_name='Nombre del Alumno')),
                ('grado', models.CharField(max_length=50, verbose_name='Grado')),
                ('materia', models.CharField(max_length=100, verbose_name='Materia')),
                ('docente', models.CharField(max_length=100, verbose_name='Docente')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reporta')),
            ],
            options={
                'verbose_name': 'Reporte Informativo',
                'verbose_name_plural': 'Reportes Informativos',
                'ordering': ['-fecha'],
            },
        ),
    ]
