# Generated by Django 5.0.14 on 2025-09-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaDocenteBilingue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100, verbose_name='Materia')),
                ('docente', models.CharField(max_length=100, verbose_name='Docente')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Materia-Docente Bilingüe',
                'verbose_name_plural': 'Materias-Docentes Bilingüe',
                'ordering': ['materia', 'docente'],
            },
        ),
        migrations.CreateModel(
            name='MateriaDocenteColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100, verbose_name='Materia')),
                ('docente', models.CharField(max_length=100, verbose_name='Docente')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Materia-Docente Colegio',
                'verbose_name_plural': 'Materias-Docentes Colegio',
                'ordering': ['materia', 'docente'],
            },
        ),
    ]
