# Generated by Django 5.0.14 on 2025-09-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducta', '0002_materiadocentebilingue_materiadocentecolegio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incisoconductual',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Descripción del inciso'),
        ),
    ]
