# Generated by Django 5.0.14 on 2025-09-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducta', '0003_alter_incisoconductual_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteconductual',
            name='grave',
        ),
        migrations.RemoveField(
            model_name='reporteconductual',
            name='inciso_grave',
        ),
        migrations.RemoveField(
            model_name='reporteconductual',
            name='inciso_leve',
        ),
        migrations.RemoveField(
            model_name='reporteconductual',
            name='inciso_muy_grave',
        ),
        migrations.RemoveField(
            model_name='reporteconductual',
            name='leve',
        ),
        migrations.RemoveField(
            model_name='reporteconductual',
            name='muy_grave',
        ),
        migrations.AddField(
            model_name='reporteconductual',
            name='incisos_grave',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo': 'grave'}, related_name='conductuales_grave', to='conducta.incisoconductual', verbose_name='Incisos Grave'),
        ),
        migrations.AddField(
            model_name='reporteconductual',
            name='incisos_leve',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo': 'leve'}, related_name='conductuales_leve', to='conducta.incisoconductual', verbose_name='Incisos Leve'),
        ),
        migrations.AddField(
            model_name='reporteconductual',
            name='incisos_muygrave',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo': 'muy_grave'}, related_name='conductuales_muygrave', to='conducta.incisoconductual', verbose_name='Incisos Muy Grave'),
        ),
    ]
