# Generated by Django 5.0.14 on 2025-09-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducta', '0004_remove_reporteconductual_grave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='coordinador_firma',
            field=models.CharField(blank=True, help_text='Nombre del coordinador que aprobó/firmó el reporte.', max_length=100, null=True, verbose_name='Coordinador que aprueba'),
        ),
        migrations.AddField(
            model_name='reporteconductual',
            name='coordinador_firma',
            field=models.CharField(blank=True, help_text='Nombre del coordinador que aprobó/firmó el reporte.', max_length=100, null=True, verbose_name='Coordinador que aprueba'),
        ),
        migrations.AddField(
            model_name='reporteinformativo',
            name='coordinador_firma',
            field=models.CharField(blank=True, help_text='Nombre del coordinador que aprobó/firmó el reporte.', max_length=100, null=True, verbose_name='Coordinador que aprueba'),
        ),
    ]
