# Generated by Django 5.0.14 on 2025-09-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducta', '0005_progressreport_coordinador_firma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('revisando', 'Revisando'), ('revisado', 'Revisado'), ('aprobado', 'Aprobado')], default='enviado', max_length=20, verbose_name='Estado del reporte'),
        ),
        migrations.AddField(
            model_name='reporteconductual',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('revisando', 'Revisando'), ('revisado', 'Revisado'), ('aprobado', 'Aprobado')], default='enviado', max_length=20, verbose_name='Estado del reporte'),
        ),
        migrations.AddField(
            model_name='reporteinformativo',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('revisando', 'Revisando'), ('revisado', 'Revisado'), ('aprobado', 'Aprobado')], default='enviado', max_length=20, verbose_name='Estado del reporte'),
        ),
    ]
