# Generated by Django 5.0.14 on 2025-09-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducta', '0006_progressreport_estado_reporteconductual_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='comentario_coordinador',
            field=models.TextField(blank=True, help_text='Observación, recomendación o motivo de la revisión/aprobación.', null=True, verbose_name='Comentario del Coordinador'),
        ),
        migrations.AddField(
            model_name='reporteconductual',
            name='comentario_coordinador',
            field=models.TextField(blank=True, help_text='Observación, recomendación o motivo de la revisión/aprobación.', null=True, verbose_name='Comentario del Coordinador'),
        ),
        migrations.AddField(
            model_name='reporteinformativo',
            name='comentario_coordinador',
            field=models.TextField(blank=True, help_text='Observación, recomendación o motivo de la revisión/aprobación.', null=True, verbose_name='Comentario del Coordinador'),
        ),
    ]
