# Generated by Django 5.0.14 on 2025-09-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducta', '0007_progressreport_comentario_coordinador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='materias_json',
            field=models.JSONField(blank=True, default=list, verbose_name='Detalle materias'),
        ),
    ]
