# Generated by Django 5.1.7 on 2025-03-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas_billingue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Appointment_bl',
        ),
        migrations.RenameModel(
            old_name='Grade',
            new_name='Grade_bl',
        ),
        migrations.RenameModel(
            old_name='Relationship',
            new_name='Relationship_bl',
        ),
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Schedule_bl',
        ),
        migrations.RenameModel(
            old_name='Subject',
            new_name='Subject_bl',
        ),
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Teacher_bl',
        ),
    ]
