# Generated by Django 5.1.7 on 2025-03-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_billingue', '0002_rename_appointment_appointment_bl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_bl',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes'), ('Saturday', 'Sábado'), ('Sunday', 'Domingo')], max_length=30),
        ),
    ]
