# Generated by Django 5.1.7 on 2025-03-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_billingue', '0003_alter_schedule_bl_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_bl',
            name='day_of_week',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=30),
        ),
    ]
