# Generated by Django 5.1.7 on 2025-05-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True, verbose_name='ID Computadora')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serie', models.CharField(max_length=100, verbose_name='Serie')),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True, verbose_name='IP')),
                ('asignado_a', models.CharField(max_length=100, verbose_name='Asignado a')),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
                ('grado', models.CharField(max_length=50, verbose_name='Grado')),
                ('fecha_instalado', models.DateField(verbose_name='Fecha de Instalación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='DataShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True, verbose_name='ID DataShow')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serie', models.CharField(max_length=100, verbose_name='Serie')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('cable_corriente', models.BooleanField(default=False, verbose_name='Cable Corriente')),
                ('hdmi', models.BooleanField(default=False, verbose_name='HDMI')),
                ('vga', models.BooleanField(default=False, verbose_name='VGA')),
                ('extension', models.BooleanField(default=False, verbose_name='Extensión')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True, verbose_name='ID Impresora')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serie', models.CharField(max_length=100, verbose_name='Serie')),
                ('asignado_a', models.CharField(max_length=100, verbose_name='Asignado a')),
                ('nivel_tinta', models.CharField(max_length=50, verbose_name='Nivel de Tinta')),
                ('ultima_vez_llenado', models.DateField(verbose_name='Última vez de llenado')),
                ('cantidad_impresiones', models.PositiveIntegerField(verbose_name='Cantidad de impresiones')),
                ('a_color', models.BooleanField(default=False, verbose_name='A color')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True, verbose_name='ID Router')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serie', models.CharField(max_length=100, verbose_name='Serie')),
                ('nombre_router', models.CharField(max_length=100, verbose_name='Nombre del Router')),
                ('clave_router', models.CharField(max_length=100, verbose_name='Clave del Router')),
                ('ip_asignada', models.GenericIPAddressField(unpack_ipv4=True, verbose_name='IP Asignada')),
                ('ip_uso', models.GenericIPAddressField(unpack_ipv4=True, verbose_name='IP de Uso')),
                ('ubicado', models.CharField(max_length=100, verbose_name='Ubicado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Televisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True, verbose_name='ID Televisor')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serie', models.CharField(max_length=100, verbose_name='Serie')),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True, verbose_name='IP')),
                ('grado', models.CharField(max_length=50, verbose_name='Grado')),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
        ),
    ]
