# Generated by Django 5.0.14 on 2025-06-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_computadora_datashow_impresora_router_televisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='computadora',
            name='category',
            field=models.CharField(blank=True, choices=[('Equipo Informatico', 'Equipo Informatico'), ('Equipo de poyecion', 'Equipo de poyecion'), ('Equipo de red', 'Equipo de red'), ('Equipo digital', 'Equipo digital'), ('Equipo de impresion', 'Equipo de impresion')], max_length=100, null=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='datashow',
            name='category',
            field=models.CharField(blank=True, choices=[('Equipo Informatico', 'Equipo Informatico'), ('Equipo de poyecion', 'Equipo de poyecion'), ('Equipo de red', 'Equipo de red'), ('Equipo digital', 'Equipo digital'), ('Equipo de impresion', 'Equipo de impresion')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impresora',
            name='category',
            field=models.CharField(blank=True, choices=[('Equipo Informatico', 'Equipo Informatico'), ('Equipo de poyecion', 'Equipo de poyecion'), ('Equipo de red', 'Equipo de red'), ('Equipo digital', 'Equipo digital'), ('Equipo de impresion', 'Equipo de impresion')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='category',
            field=models.CharField(blank=True, choices=[('Equipo Informatico', 'Equipo Informatico'), ('Equipo de poyecion', 'Equipo de poyecion'), ('Equipo de red', 'Equipo de red'), ('Equipo digital', 'Equipo digital'), ('Equipo de impresion', 'Equipo de impresion')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='televisor',
            name='category',
            field=models.CharField(blank=True, choices=[('Equipo Informatico', 'Equipo Informatico'), ('Equipo de poyecion', 'Equipo de poyecion'), ('Equipo de red', 'Equipo de red'), ('Equipo digital', 'Equipo digital'), ('Equipo de impresion', 'Equipo de impresion')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('Equipo Informatico', 'Equipo Informatico'), ('Equipo de poyecion', 'Equipo de poyecion'), ('Equipo de red', 'Equipo de red'), ('Equipo digital', 'Equipo digital'), ('Equipo de impresion', 'Equipo de impresion')], max_length=100, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='details',
            field=models.CharField(max_length=255, verbose_name='Detalles'),
        ),
    ]
