# Generated by Django 5.0.14 on 2025-11-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_inventoryitem_created_at_computadora_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadora',
            name='grupo',
            field=models.PositiveIntegerField(blank=True, help_text='Número de grupo para clasificar computadoras', null=True, verbose_name='Grupo'),
        ),
    ]
