# Generated by Django 5.1.7 on 2025-03-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_colegio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_col',
            name='day_of_week',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher_col',
            name='area',
            field=models.CharField(choices=[('Matematicas Bachillerato', 'Matematicas Bachillerato'), ('Matematicas basica', 'Matematicas basica'), ('Generales', 'Generales'), ('Ingles Basico', 'Ingles Basico')], max_length=50),
        ),
    ]
