# Generated by Django 5.1.7 on 2025-03-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(db_column='gen_city_id', primary_key=True, serialize=False)),
                ('zip_code', models.CharField(blank=True, db_column='zip_code', max_length=10, null=True, verbose_name='Código Postal')),
                ('name', models.CharField(blank=True, db_column='city', max_length=100, null=True, verbose_name='Nombre de la Ciudad')),
            ],
            options={
                'db_table': 'tbl_gen_city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(db_column='gen_country_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='country', max_length=100, verbose_name='Nombre del País')),
            ],
            options={
                'db_table': 'tbl_gen_country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directed',
            fields=[
                ('id', models.AutoField(db_column='gen_directed_id', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='description', max_length=50, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Directed',
                'verbose_name_plural': 'Directed',
                'db_table': 'tbl_gen_directed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(db_column='gen_title_id', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='description', max_length=50, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
                'db_table': 'tbl_gen_title',
                'managed': False,
            },
        ),
    ]
