# Generated by Django 5.1.7 on 2025-03-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.AutoField(db_column='spn_correspondence_id', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'tbl_spn_correspondence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Godfather',
            fields=[
                ('id', models.AutoField(db_column='spn_godfather_id', primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('diploma', models.DateTimeField(blank=True, null=True, verbose_name='Diploma')),
                ('money_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Dinero')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Monto')),
                ('desactivated', models.BooleanField(default=False, verbose_name='Desactivado')),
            ],
            options={
                'db_table': 'tbl_spn_godfather',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(db_column='spn_income_id', primary_key=True, serialize=False)),
                ('origin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Origen')),
                ('currency_code', models.CharField(max_length=50, verbose_name='Código de Moneda')),
                ('amount', models.FloatField(verbose_name='Monto')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('receipt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Recibo')),
                ('check_number', models.CharField(blank=True, db_column='check', max_length=20, null=True, verbose_name='Número de Cheque')),
                ('text1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto 1')),
                ('text2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto 2')),
                ('receipt_number', models.BooleanField(default=False, verbose_name='Número de Recibo')),
                ('payment_mail', models.BooleanField(default=False, verbose_name='Correo de Pago')),
            ],
            options={
                'db_table': 'tbl_spn_income',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(db_column='spn_sponsors_id', primary_key=True, serialize=False)),
                ('last_name_1', models.CharField(db_column='last_name_1', max_length=100, verbose_name='Apellido 1')),
                ('last_name_2', models.CharField(blank=True, db_column='last_name_2', max_length=50, null=True, verbose_name='Apellido 2')),
                ('first_name_1', models.CharField(blank=True, db_column='first_name_1', max_length=50, null=True, verbose_name='Nombre 1')),
                ('first_name_2', models.CharField(blank=True, db_column='first_name_2', max_length=50, null=True, verbose_name='Nombre 2')),
                ('free_union', models.BooleanField(db_column='free_union', default=False, verbose_name='Unión Libre')),
                ('profession', models.CharField(blank=True, db_column='profession', max_length=50, null=True, verbose_name='Profesión')),
                ('address', models.CharField(blank=True, db_column='address', max_length=100, null=True, verbose_name='Dirección')),
                ('street', models.CharField(blank=True, db_column='street', max_length=100, null=True, verbose_name='Calle')),
                ('phone_1', models.CharField(blank=True, db_column='phone_1', max_length=50, null=True, verbose_name='Teléfono 1')),
                ('phone_2', models.CharField(blank=True, db_column='phone_2', max_length=50, null=True, verbose_name='Teléfono 2')),
                ('fax', models.CharField(blank=True, db_column='fax', max_length=50, null=True, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=50, null=True, verbose_name='Correo Electrónico')),
                ('email_2', models.EmailField(blank=True, db_column='email_2', max_length=50, null=True, verbose_name='Correo Electrónico 2')),
                ('email_3', models.EmailField(blank=True, db_column='email_3', max_length=50, null=True, verbose_name='Correo Electrónico 3')),
                ('report_email', models.BooleanField(db_column='report_email', default=False, verbose_name='Reporte Email (si no paga 3 años)')),
                ('only_email', models.BooleanField(db_column='only_email', default=False, verbose_name='Solo Email (no quiere correo)')),
                ('only_easter_rep', models.BooleanField(db_column='only_easter_rep', default=False, verbose_name='Solo Email OB (solo para Alemania)')),
                ('financial_report', models.BooleanField(db_column='financial_report', default=False, verbose_name='Reporte Financiero (solo Insiders)')),
                ('language', models.CharField(blank=True, db_column='language', max_length=50, null=True, verbose_name='Idioma Reporte')),
                ('annex', models.CharField(blank=True, db_column='annex', max_length=100, null=True, verbose_name='Anexo')),
                ('contact', models.CharField(blank=True, db_column='contact', max_length=100, null=True, verbose_name='Contacto')),
                ('addressed_to', models.CharField(blank=True, db_column='addressed_to', max_length=100, null=True, verbose_name='Dirigido Carta')),
                ('addressed_to_2', models.CharField(blank=True, db_column='addressed_to_2', max_length=100, null=True, verbose_name='Dirigido Carta Aled')),
                ('visitor', models.BooleanField(db_column='visitor', default=False, verbose_name='Visitante')),
                ('visitor_date', models.DateTimeField(blank=True, db_column='visitor_date', null=True, verbose_name='Fecha de Visita')),
                ('sponsor', models.BooleanField(db_column='sponsor', default=False, verbose_name='Padrino')),
                ('godfather', models.BooleanField(db_column='godfather', default=False, verbose_name='Bienhechor')),
                ('sponsorship', models.CharField(blank=True, db_column='sponsorship', max_length=50, null=True, verbose_name='Padrinazgo')),
                ('member', models.BooleanField(db_column='member', default=False, verbose_name='Miembro')),
                ('former_volunteer', models.BooleanField(db_column='former_volunteer', default=False, verbose_name='Ex Voluntario')),
                ('volunt_dep_date', models.DateTimeField(blank=True, db_column='volunt_dep_date', null=True, verbose_name='Fecha Egr Vol')),
                ('no_correspondence', models.BooleanField(db_column='no_correspondence', default=False, verbose_name='No Corresp')),
                ('deceased', models.BooleanField(db_column='deceased', default=False, verbose_name='Fallecido')),
                ('deactivated', models.BooleanField(db_column='deactivated', default=False, verbose_name='Desactivado')),
                ('expect_reaction', models.BooleanField(db_column='expect_reaction', default=False, verbose_name='Esperar Reac.')),
                ('bad_address', models.BooleanField(db_column='bad_address', default=False, verbose_name='Dirección Mala')),
                ('private', models.BooleanField(db_column='private', default=False, verbose_name='Privado')),
                ('first_contact', models.DateTimeField(blank=True, db_column='first_contact', null=True, verbose_name='Primer Contacto')),
                ('last_contact', models.DateTimeField(blank=True, db_column='last_contact', null=True, verbose_name='Último Contacto')),
                ('note_1', models.TextField(blank=True, db_column='note_1', null=True, verbose_name='Nota 1')),
                ('note_2', models.TextField(blank=True, db_column='note_2', null=True, verbose_name='Nota 2')),
                ('date_of_birth', models.DateTimeField(blank=True, db_column='date_of_birth', null=True, verbose_name='Fecha de Nacim 1')),
                ('date_of_birth_2', models.DateTimeField(blank=True, db_column='date_of_birth_2', null=True, verbose_name='Fecha de Nacim 2')),
                ('gender', models.CharField(blank=True, db_column='gender', max_length=10, null=True, verbose_name='Sexo')),
                ('civil_status', models.CharField(blank=True, db_column='civil_status', max_length=12, null=True, verbose_name='Estado Civil')),
                ('nationality', models.CharField(blank=True, db_column='nationality', max_length=50, null=True, verbose_name='Nacionalidad')),
                ('imprimir', models.BooleanField(db_column='imprimir', default=False, verbose_name='Imprimir')),
                ('deactivate_soon', models.BooleanField(db_column='deactivate_soon', default=False, verbose_name='Desact Prox')),
                ('recog_2010', models.BooleanField(db_column='recog_2010', default=False, verbose_name='Recon 2010')),
                ('recog_2020_blanket', models.BooleanField(db_column='recog_2020_blanket', default=False, verbose_name='Recon 2020 Manta')),
                ('recog_2020_plate', models.BooleanField(db_column='recog_2020_plate', default=False, verbose_name='Recon 2020 Plato')),
                ('padrino_ch_d', models.CharField(blank=True, choices=[('Alemania', 'Alemania'), ('Austria', 'Austria'), ('España', 'España'), ('Holanda', 'Holanda'), ('Portugal', 'Portugal'), ('Suiza', 'Suiza'), ('USA', 'USA'), ('Honduras', 'Honduras'), ('Guatemala', 'Guatemala'), ('Francia', 'Francia'), ('Canada', 'Canada'), ('Belgica', 'Belgica'), ('Suecia', 'Suecia'), ('Escocia', 'Escocia'), ('Colombia', 'Colombia'), ('Wales U.K.', 'Wales U.K.'), ('Costa Rica C.A.', 'Costa Rica C.A.'), ('Japon', 'Japon'), ('Italia', 'Italia'), ('n/d', 'n/d'), ('U.A.E.', 'U.A.E.'), ('Mexico', 'Mexico'), ('Irlanda', 'Irlanda')], db_column='padrino_ch_d', max_length=50, null=True, verbose_name='Padrino CH/D')),
            ],
            options={
                'db_table': 'tbl_spn_sponsors',
                'managed': False,
            },
        ),
    ]
