# Generated by Django 5.1.7 on 2025-04-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Grado')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Medicamento')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('proveedor', models.CharField(max_length=100, verbose_name='Proveedor')),
                ('cantidad_existente', models.PositiveIntegerField(verbose_name='Cantidad Existente')),
                ('cantidad_usado', models.PositiveIntegerField(verbose_name='Cantidad Usada')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Item de Inventario',
                'verbose_name_plural': 'Inventarios de Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Profesional')),
            ],
        ),
        migrations.CreateModel(
            name='AtencionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=100, verbose_name='Nombre del Estudiante')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('tratamiento', models.TextField(verbose_name='Tratamiento')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfermeria.grado', verbose_name='Grado')),
                ('atendido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfermeria.medico', verbose_name='Atendido por')),
            ],
            options={
                'verbose_name': 'Atención Médica',
                'verbose_name_plural': 'Atenciones Médicas',
            },
        ),
    ]
