# Generated by Django 5.1.7 on 2025-04-23 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Responsable')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
            },
        ),
        migrations.AlterModelOptions(
            name='inventariomedicamento',
            options={'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
        migrations.RemoveField(
            model_name='inventariomedicamento',
            name='cantidad_usado',
        ),
        migrations.RemoveField(
            model_name='inventariomedicamento',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='inventariomedicamento',
            name='total',
        ),
        migrations.AlterField(
            model_name='inventariomedicamento',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfermeria.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='UsoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.PositiveIntegerField(verbose_name='Cantidad Usada')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('fecha_uso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Uso')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='enfermeria.inventariomedicamento')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfermeria.responsable', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Uso de Medicamento',
                'verbose_name_plural': 'Usos de Medicamentos',
            },
        ),
    ]
