# Generated by Django 5.0.14 on 2025-07-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0002_presentacion_alter_grado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblPrsDtosGen',
            fields=[
                ('PersonaID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Nombre1', models.CharField(blank=True, max_length=100, null=True)),
                ('Nombre2', models.CharField(blank=True, max_length=100, null=True)),
                ('Apellido1', models.CharField(blank=True, max_length=100, null=True)),
                ('Apellido2', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=254, null=True)),
                ('Email2', models.CharField(blank=True, max_length=254, null=True)),
                ('Email3', models.CharField(blank=True, max_length=254, null=True)),
                ('alum', models.IntegerField(blank=True, db_column='alum', null=True)),
            ],
            options={
                'db_table': 'tblPrsDtosGen',
                'managed': False,
            },
        ),
    ]
