# Generated by Django 5.0.14 on 2025-10-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(help_text='ID exacto del empleado (BioTime/zkbiotime)', max_length=20, unique=True, verbose_name='ID Empleado')),
                ('nombre', models.CharField(blank=True, help_text='Solo referencia, se puede llenar automáticamente al guardar', max_length=100, verbose_name='Nombre Empleado')),
                ('entrada_manana', models.TimeField(verbose_name='Entrada Mañana')),
                ('salida_manana', models.TimeField(verbose_name='Salida Mañana')),
                ('entrada_tarde', models.TimeField(blank=True, null=True, verbose_name='Entrada Tarde')),
                ('salida_tarde', models.TimeField(blank=True, null=True, verbose_name='Salida Tarde')),
            ],
            options={
                'verbose_name': 'Horario de Empleado',
                'verbose_name_plural': 'Horarios de Empleados',
            },
        ),
    ]
