# Generated by Django 5.0.14 on 2025-10-29 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(db_index=True, max_length=20, verbose_name='Código empleado')),
                ('nombre_empleado', models.CharField(blank=True, max_length=200, verbose_name='Nombre empleado (cache)')),
                ('fecha_inicio', models.DateField(verbose_name='Vigente desde')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Asignación de plantilla',
                'verbose_name_plural': 'Asignaciones de plantilla',
                'db_table': 'reloj_employee_schedule_assignment',
            },
        ),
        migrations.CreateModel(
            name='ScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('trabaja', models.BooleanField(default=True, verbose_name='Trabaja este día')),
                ('entrada_manana', models.TimeField(blank=True, null=True, verbose_name='Entrada mañana')),
                ('salida_manana', models.TimeField(blank=True, null=True, verbose_name='Salida mañana')),
                ('entrada_tarde', models.TimeField(blank=True, null=True, verbose_name='Entrada tarde')),
                ('salida_tarde', models.TimeField(blank=True, null=True, verbose_name='Salida tarde')),
            ],
            options={
                'verbose_name': 'Regla de día',
                'verbose_name_plural': 'Reglas de día',
                'db_table': 'reloj_schedule_rule',
                'ordering': ['template', 'weekday'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre de plantilla')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Plantilla de horario',
                'verbose_name_plural': 'Plantillas de horario',
                'db_table': 'reloj_schedule_template',
            },
        ),
        migrations.DeleteModel(
            name='EmployeeSchedule',
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='reloj.scheduletemplate'),
        ),
        migrations.AddField(
            model_name='employeescheduleassignment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='reloj.scheduletemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='schedulerule',
            unique_together={('template', 'weekday')},
        ),
        migrations.AddIndex(
            model_name='employeescheduleassignment',
            index=models.Index(fields=['emp_code', 'fecha_inicio', 'fecha_fin'], name='reloj_emplo_emp_cod_d7d3d7_idx'),
        ),
    ]
