# Generated by Django 5.0.14 on 2025-10-29 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj', '0002_employeescheduleassignment_schedulerule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(db_index=True, max_length=20, verbose_name='Código empleado')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('minutos_calculados', models.PositiveIntegerField(default=0, verbose_name='Minutos extra calculados')),
                ('minutos_autorizados', models.PositiveIntegerField(default=0, verbose_name='Minutos extra autorizados')),
                ('comentario', models.CharField(blank=True, max_length=255, verbose_name='Comentario')),
                ('status', models.CharField(choices=[('PEND', 'Pendiente'), ('APPR', 'Aprobado'), ('REJC', 'Rechazado')], default='PEND', max_length=4, verbose_name='Estado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de autorización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por')),
            ],
            options={
                'verbose_name': 'Tiempo extra',
                'verbose_name_plural': 'Tiempos extra',
                'db_table': 'reloj_overtime_request',
                'ordering': ['-fecha', 'emp_code'],
                'indexes': [models.Index(fields=['emp_code', 'fecha'], name='reloj_overt_emp_cod_4e9f9a_idx'), models.Index(fields=['status'], name='reloj_overt_status_1af811_idx')],
                'unique_together': {('emp_code', 'fecha')},
            },
        ),
    ]
