# Generated by Django 5.0.14 on 2025-10-31 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj', '0003_overtimerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeescheduleassignment',
            options={'ordering': ['-activo', 'emp_code', '-fecha_inicio'], 'verbose_name': 'Asignación de plantilla', 'verbose_name_plural': 'Asignaciones de plantilla'},
        ),
        migrations.AlterModelOptions(
            name='scheduletemplate',
            options={'ordering': ['nombre'], 'verbose_name': 'Plantilla de horario', 'verbose_name_plural': 'Plantillas de horario'},
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha de feriado')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feriados_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'db_table': 'reloj_feriado',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SabadoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('descripcion', models.CharField(default='Escuela para padres', max_length=255, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sabados_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Sábado especial',
                'verbose_name_plural': 'Sábados especiales',
                'db_table': 'reloj_sabado_especial',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PermisoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(db_index=True, max_length=20, verbose_name='Código empleado')),
                ('nombre_empleado', models.CharField(max_length=120, verbose_name='Nombre empleado')),
                ('fecha_inicio', models.DateField(verbose_name='Desde')),
                ('fecha_fin', models.DateField(verbose_name='Hasta')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('comentario_autorizacion', models.TextField(blank=True, verbose_name='Comentario autorización')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_autorizados', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Permiso de empleado',
                'verbose_name_plural': 'Permisos de empleados',
                'db_table': 'reloj_permiso_empleado',
                'ordering': ['-fecha_inicio', 'emp_code'],
                'indexes': [models.Index(fields=['emp_code', 'fecha_inicio', 'fecha_fin'], name='reloj_permi_emp_cod_31965c_idx'), models.Index(fields=['aprobado'], name='reloj_permi_aprobad_11c2f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TiempoCompensatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(db_index=True, max_length=20, verbose_name='Código empleado')),
                ('nombre_empleado', models.CharField(max_length=120, verbose_name='Nombre empleado')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('minutos_registrados', models.PositiveIntegerField(default=0, verbose_name='Minutos registrados')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('autorizado_en', models.DateTimeField(blank=True, null=True, verbose_name='Autorizado en')),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('APPR', 'Aprobado'), ('REJC', 'Rechazado')], default='PEND', max_length=4, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiempos_compensatorio_autorizados', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiempos_compensatorio_creados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Tiempo compensatorio',
                'verbose_name_plural': 'Tiempos compensatorios',
                'db_table': 'reloj_tiempo_compensatorio',
                'ordering': ['-fecha', '-creado_en'],
                'indexes': [models.Index(fields=['emp_code', 'fecha'], name='reloj_tiemp_emp_cod_c19552_idx'), models.Index(fields=['estado'], name='reloj_tiemp_estado_8ca982_idx')],
            },
        ),
    ]
