# Generated by Django 5.0.14 on 2025-07-21 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.IntegerField(verbose_name='PersonaID')),
                ('semana_inicio', models.DateField(verbose_name='Semana desde')),
                ('semana_fin', models.DateField(verbose_name='Semana hasta')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Progress Report',
                'verbose_name_plural': 'Progress Reports',
            },
        ),
        migrations.CreateModel(
            name='ReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignacion', models.CharField(blank=True, max_length=200, verbose_name='Asignación')),
                ('observacion', models.TextField(blank=True, verbose_name='Comentario/Observación')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informes_bl.materia', verbose_name='Materia')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='informes_bl.progressreport', verbose_name='Reporte')),
            ],
            options={
                'verbose_name': 'Entrada de Reporte',
                'verbose_name_plural': 'Entradas de Reporte',
                'ordering': ['materia'],
            },
        ),
    ]
